// @vitest-environment happy-dom
/**
 * StageAdvanceModal — the gate error must own up to auto-generated tasks (#419).
 *
 * The 422 gate fires on high-priority tasks the *system* seeded when the deal
 * entered the stage, but the modal said only "N required tasks still open" —
 * which reads as "you forgot something" for work the agent never created. The
 * blocking payload now carries `source` + `stage_context`, so the modal names
 * them as auto-generated and says which stage generated them.
 */
import { describe, it, expect, vi } from "vitest";
import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { StageAdvanceModal } from "@/components/deal/StageAdvanceModal";
import type { Deal, DealStage } from "@/lib/types";

const DEAL = {
  id: "9a1a1b2c-3d4e-4f50-8a9b-0c1d2e3f4a5b",
  clientName: "Jane Buyer",
  type: "buy",
  stage: "active_search",
  property: { address: "12 Oak St", city: "Birmingham", state: "AL", zip: "35203", price: 400000 },
} as unknown as Deal;

type BlockingTask = {
  id: string;
  title: string;
  source?: string | null;
  stage_context?: string | null;
};

/**
 * The gate-error assertions below are stage-agnostic, so they run against
 * `under_contract` — advancing to `offer_active` now additionally requires the
 * offer property + amount (#410), which would otherwise disable the footer
 * buttons these tests click. The #410 fields have their own describe block.
 */
function renderModal(
  blockingTasks: BlockingTask[] | null,
  nextStage: DealStage = "under_contract",
) {
  const onConfirm = vi.fn();
  render(
    <StageAdvanceModal
      deal={DEAL}
      nextStage={nextStage}
      gateError={blockingTasks ? { blockingTasks } : null}
      onConfirm={onConfirm}
      onCancel={vi.fn()}
    />,
  );
  return { onConfirm };
}

const AI_TASK: BlockingTask = {
  id: "t1",
  title: "Send pre-approval checklist — Jane Buyer",
  source: "ai",
  stage_context: "active_search",
};

describe("StageAdvanceModal gate error", () => {
  it("says an auto-generated blocker was generated by the stage it came from", () => {
    renderModal([AI_TASK]);

    expect(screen.getByText(/1 required task still open/i)).toBeTruthy();
    expect(screen.getByText(AI_TASK.title)).toBeTruthy();
    // Names them as the app's own, and names the stage that generated them.
    expect(screen.getByText(/generated automatically/i).textContent).toMatch(
      /Active Search/i,
    );
  });

  it("does not call manually-created blockers auto-generated", () => {
    renderModal([
      { id: "t2", title: "Call the listing agent", source: "manual", stage_context: "active_search" },
    ]);

    expect(screen.getByText("Call the listing agent")).toBeTruthy();
    expect(screen.queryByText(/generated automatically/i)).toBeNull();
  });

  it("marks only the auto-generated task in a mixed list", () => {
    renderModal([
      AI_TASK,
      { id: "t3", title: "Call the listing agent", source: "manual", stage_context: "active_search" },
    ]);

    expect(screen.getByText(/2 required tasks still open/i)).toBeTruthy();
    // Exactly one row is badged as auto-generated.
    expect(screen.getAllByText(/^auto$/i).length).toBe(1);
    expect(screen.getByText(/generated automatically/i).textContent).toMatch(
      /1 of these/i,
    );
  });

  it("falls back to the deal's current stage when stage_context is null", () => {
    renderModal([{ id: "t4", title: "Orphaned auto task", source: "ai", stage_context: null }]);

    expect(screen.getByText(/generated automatically/i).textContent).toMatch(
      /Active Search/i,
    );
  });

  it("still offers Force Advance and confirms with force=true", async () => {
    const { onConfirm } = renderModal([AI_TASK]);

    await userEvent.click(screen.getByRole("button", { name: /force advance/i }));
    expect(onConfirm).toHaveBeenCalledTimes(1);
    expect(onConfirm.mock.calls[0][1]).toBe(true);
  });

  it("renders no gate block at all when there is no gate error", () => {
    renderModal(null);

    expect(screen.queryByText(/required task/i)).toBeNull();
    expect(screen.queryByText(/generated automatically/i)).toBeNull();
    expect(screen.getByRole("button", { name: /confirm & advance/i })).toBeTruthy();
  });
});

// ─── #410: Offer Active must capture the property and the amount ─────────────
/**
 * Advancing to Offer Active asked only for a client message, so the app
 * recorded nothing about the offer and the banner guessed the house from
 * whichever listing the buyer had tapped "Make an Offer" on. The modal now
 * requires both, and hands them to onConfirm as its third argument.
 */
const PROPERTIES = [
  { id: "p-1", address: "12 Oak St", city: "Birmingham", state: "AL", price: 400000 },
  { id: "p-2", address: "9 Willow Ln", city: "Homewood", state: "AL", price: 325000 },
];

function renderOfferModal(
  properties: typeof PROPERTIES = PROPERTIES,
  nextStage: DealStage = "offer_active",
) {
  const onConfirm = vi.fn();
  render(
    <StageAdvanceModal
      deal={DEAL}
      nextStage={nextStage}
      properties={properties}
      gateError={null}
      onConfirm={onConfirm}
      onCancel={vi.fn()}
    />,
  );
  return { onConfirm };
}

const confirmButton = () =>
  screen.getByRole("button", { name: /confirm & advance/i }) as HTMLButtonElement;

describe("StageAdvanceModal offer details (#410)", () => {
  it("renders a property picker listing every tracked property", () => {
    renderOfferModal();

    const picker = screen.getByLabelText(/property under offer/i) as HTMLSelectElement;
    expect(picker).toBeTruthy();
    // Two properties + the "Select a property…" placeholder.
    expect(picker.options.length).toBe(3);
    expect(screen.getByRole("option", { name: /12 Oak St/ })).toBeTruthy();
    expect(screen.getByRole("option", { name: /9 Willow Ln/ })).toBeTruthy();
  });

  it("disables confirm until BOTH the property and the amount are set", async () => {
    renderOfferModal();
    const amount = screen.getByLabelText(/offer amount/i);

    expect(confirmButton().disabled).toBe(true);

    // Amount alone is not enough.
    await userEvent.type(amount, "385000");
    expect(confirmButton().disabled).toBe(true);

    // Property alone is not enough either.
    await userEvent.clear(amount);
    await userEvent.selectOptions(screen.getByLabelText(/property under offer/i), "p-2");
    expect(confirmButton().disabled).toBe(true);

    // Both → enabled.
    await userEvent.type(amount, "310000");
    expect(confirmButton().disabled).toBe(false);
  });

  it("rejects a zero offer amount", async () => {
    renderOfferModal();
    await userEvent.selectOptions(screen.getByLabelText(/property under offer/i), "p-1");
    await userEvent.type(screen.getByLabelText(/offer amount/i), "0");

    expect(confirmButton().disabled).toBe(true);
  });

  it("hands the chosen property id and amount to onConfirm", async () => {
    const { onConfirm } = renderOfferModal();

    await userEvent.selectOptions(screen.getByLabelText(/property under offer/i), "p-2");
    await userEvent.type(screen.getByLabelText(/offer amount/i), "310000");
    await userEvent.click(confirmButton());

    expect(onConfirm).toHaveBeenCalledTimes(1);
    expect(onConfirm.mock.calls[0][2]).toEqual({
      tracked_property_id: "p-2",
      offer_price: 310000,
    });
  });

  it("shows the list price so the agent can see they offered under it", async () => {
    renderOfferModal();

    await userEvent.selectOptions(screen.getByLabelText(/property under offer/i), "p-1");
    await userEvent.type(screen.getByLabelText(/offer amount/i), "385000");

    const hint = screen.getByText(/listed at/i);
    expect(hint.textContent).toMatch(/\$400,000/);
    expect(hint.textContent).toMatch(/\$15,000\s*under/);
  });

  it("says what to do when the deal has no tracked properties yet", () => {
    renderOfferModal([]);

    expect(screen.queryByLabelText(/property under offer/i)).toBeNull();
    expect(screen.getByText(/Properties tab/i)).toBeTruthy();
    expect(confirmButton().disabled).toBe(true);
  });

  it("leaves every other stage exactly as it was — no offer fields, confirm enabled", () => {
    renderOfferModal(PROPERTIES, "under_contract");

    expect(screen.queryByLabelText(/property under offer/i)).toBeNull();
    expect(screen.queryByLabelText(/offer amount/i)).toBeNull();
    expect(screen.queryByText(/offer details/i)).toBeNull();
    expect(confirmButton().disabled).toBe(false);
  });

  it("still drafts and sends the client message alongside the offer", async () => {
    const { onConfirm } = renderOfferModal();

    await userEvent.selectOptions(screen.getByLabelText(/property under offer/i), "p-1");
    await userEvent.type(screen.getByLabelText(/offer amount/i), "390000");
    await userEvent.click(confirmButton());

    expect(typeof onConfirm.mock.calls[0][0]).toBe("string");
    expect((onConfirm.mock.calls[0][0] as string).length).toBeGreaterThan(0);
  });
});

/**
 * #420 — the "Will run automatically" list is a FORECAST.
 *
 * Every line rendered with a green `CheckCircle2` before the agent had
 * confirmed anything, so work that had not happened — and might never happen,
 * since Cancel is right there — was drawn exactly like completed work. One
 * convention across the app: a green check means the thing actually happened.
 */
describe("StageAdvanceModal — 'will run automatically' is a forecast (#420)", () => {
  it("renders the automation items without any completed-state icon", () => {
    renderModal(null);

    const list = screen.getByTestId("automation-list");
    const items = screen.getAllByTestId("automation-item");
    expect(items.length).toBeGreaterThan(0);

    // No green anywhere in the block — green is reserved for confirmed work.
    expect(list.querySelectorAll('[class*="text-green"]')).toHaveLength(0);
    for (const item of items) {
      expect(item.getAttribute("data-state")).toBe("forecast");
    }
  });

  it("words the items as things that will happen, not things that have", () => {
    renderModal(null);

    const list = screen.getByTestId("automation-list");
    // Past tense ("sent to", "auto-generated") reads as done. It isn't yet.
    expect(list.textContent).not.toMatch(/\bsent to\b/i);
    expect(list.textContent).toMatch(/when you confirm/i);
  });
});
