// @vitest-environment happy-dom
/**
 * StageAdvanceModal — the gate error must own up to auto-generated tasks (#419).
 *
 * The 422 gate fires on high-priority tasks the *system* seeded when the deal
 * entered the stage, but the modal said only "N required tasks still open" —
 * which reads as "you forgot something" for work the agent never created. The
 * blocking payload now carries `source` + `stage_context`, so the modal names
 * them as auto-generated and says which stage generated them.
 */
import { describe, it, expect, vi } from "vitest";
import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { StageAdvanceModal } from "@/components/deal/StageAdvanceModal";
import type { Deal, DealStage } from "@/lib/types";

const DEAL = {
  id: "9a1a1b2c-3d4e-4f50-8a9b-0c1d2e3f4a5b",
  clientName: "Jane Buyer",
  type: "buy",
  stage: "active_search",
  property: { address: "12 Oak St", city: "Birmingham", state: "AL", zip: "35203", price: 400000 },
} as unknown as Deal;

type BlockingTask = {
  id: string;
  title: string;
  source?: string | null;
  stage_context?: string | null;
};

function renderModal(
  blockingTasks: BlockingTask[] | null,
  nextStage: DealStage = "offer_active",
) {
  const onConfirm = vi.fn();
  render(
    <StageAdvanceModal
      deal={DEAL}
      nextStage={nextStage}
      gateError={blockingTasks ? { blockingTasks } : null}
      onConfirm={onConfirm}
      onCancel={vi.fn()}
    />,
  );
  return { onConfirm };
}

const AI_TASK: BlockingTask = {
  id: "t1",
  title: "Send pre-approval checklist — Jane Buyer",
  source: "ai",
  stage_context: "active_search",
};

describe("StageAdvanceModal gate error", () => {
  it("says an auto-generated blocker was generated by the stage it came from", () => {
    renderModal([AI_TASK]);

    expect(screen.getByText(/1 required task still open/i)).toBeTruthy();
    expect(screen.getByText(AI_TASK.title)).toBeTruthy();
    // Names them as the app's own, and names the stage that generated them.
    expect(screen.getByText(/generated automatically/i).textContent).toMatch(
      /Active Search/i,
    );
  });

  it("does not call manually-created blockers auto-generated", () => {
    renderModal([
      { id: "t2", title: "Call the listing agent", source: "manual", stage_context: "active_search" },
    ]);

    expect(screen.getByText("Call the listing agent")).toBeTruthy();
    expect(screen.queryByText(/generated automatically/i)).toBeNull();
  });

  it("marks only the auto-generated task in a mixed list", () => {
    renderModal([
      AI_TASK,
      { id: "t3", title: "Call the listing agent", source: "manual", stage_context: "active_search" },
    ]);

    expect(screen.getByText(/2 required tasks still open/i)).toBeTruthy();
    // Exactly one row is badged as auto-generated.
    expect(screen.getAllByText(/^auto$/i).length).toBe(1);
    expect(screen.getByText(/generated automatically/i).textContent).toMatch(
      /1 of these/i,
    );
  });

  it("falls back to the deal's current stage when stage_context is null", () => {
    renderModal([{ id: "t4", title: "Orphaned auto task", source: "ai", stage_context: null }]);

    expect(screen.getByText(/generated automatically/i).textContent).toMatch(
      /Active Search/i,
    );
  });

  it("still offers Force Advance and confirms with force=true", async () => {
    const { onConfirm } = renderModal([AI_TASK]);

    await userEvent.click(screen.getByRole("button", { name: /force advance/i }));
    expect(onConfirm).toHaveBeenCalledTimes(1);
    expect(onConfirm.mock.calls[0][1]).toBe(true);
  });

  it("renders no gate block at all when there is no gate error", () => {
    renderModal(null);

    expect(screen.queryByText(/required task/i)).toBeNull();
    expect(screen.queryByText(/generated automatically/i)).toBeNull();
    expect(screen.getByRole("button", { name: /confirm & advance/i })).toBeTruthy();
  });
});
